### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by Mac-Womack** [OmegaGrape/qb-suicidevest#2]
**Expected Behavior** it to beep so u know its armed and deadman switch tow ork

**Current Behavior** does nothing but equips vest

**Possible Solution** idk 

**Steps to Reproduce** i followed all steps you posted

**Detailed Description** the onlything it does is equip a vest

**Comment by Omega248** [comment]
Do you have any errors in the f8 console or the server console?

**Comment by Mac-Womack** [comment]
I fixed it but my vest is a plain black on not an explosive vest

**Comment by Omega248** [comment]
That will be an issue with the eup, you need an active subscription to the FiveM patreon for the eup to work and the number 2 in this snippet of code `SetPedComponentVariation(ped, 9, 0, 0, 2)` from the readme needs to the number of the vest in the clothing menu if you simply dropped the assets into your eup folder it will be number 2 by default but if you changed it you would need to find it.

**Comment by Mac-Womack** [comment]
Ok, thanks.
